import './KnowledgeBase.css';

export default function KnowledgeBase() {
  return (
    <section className="knowledge-base" id="knowledge-base">
      <div className="container">
        <div className="kb-header">
          <h2>Knowledge Base</h2>
          <p className="subtitle">Learn about Digital Signatures and Certification</p>
        </div>

        <div className="kb-content">
          <div className="kb-item">
            <h3>What is Digital Signature?</h3>
            <p>A digital signature is an electronic form of a signature that can be used to authenticate the identity of the sender of a message or the signer of a document, and also ensure that the original content of the message or document that has been sent is unchanged. Digital signatures are easily transportable and cannot be imitated by someone else. The ability to ensure that the original signed message arrived means that the sender cannot easily disclaim it later.</p>
          </div>

          <div className="kb-item">
            <h3>Why Digital Signature?</h3>
            <p>Since information security, authentication is the most serious issue in e-transaction and internet environment. It is the state responsibility to maintain law and order in the society likewise this is also the responsibility of the government to maintain law and order in the information technology world and specially in the internet world where lot of e-transactions are live every moment.</p>
          </div>

          <div className="kb-item">
            <h3>What is a Certifying Authority (CA)?</h3>
            <p>A trusted third-party organization or company that issues digital certificates used to create digital signatures and public-private key pairs. The role of the CA in this process is to guarantee that the individual granted the unique certificate is, in fact, who he or she claims to be.</p>
            
            <p>A CA can be within the organization itself or outside organization depending on the purpose of the certificates. A company may issue certificates to its employees for reason that only its employees can access to the company database but an internet user might request for a certificate from a well-known and trusted CA in order for him to do on-line transaction securely.</p>
          </div>

          <div className="kb-item">
            <h3>What are digital certificates?</h3>
            <p>Digital certificates are the digital equivalent (i.e. electronic format) of physical or paper certificates. Examples of physical certificates are drivers licenses, passports or membership cards. Certificates serve as identity of an individual for a certain purpose, e.g. a drivers license identifies someone who can legally drive in a particular country. Likewise, a digital certificate can be presented electronically to prove your identity or your right to access information or services on the Internet.</p>
          </div>

          <div className="kb-item">
            <h3>What exactly is a digital signature?</h3>
            <p>Just as a handwritten signature is affixed to a printed letter for verification that the letter originated from its purported sender, digital signature performs the same task for an electronic message.</p>
            
            <p>A digital signature is an encrypted version of a message digest, attached together with a message. A secure digital signature system consists of two parts: A method of signing a document such that forgery is detected, and A method of verifying that a signature was actually generated by whomever it represents.</p>
          </div>

          <div className="kb-item">
            <h3>Asymmetric/Public key vs. Symmetric/Secret key: which cryptography system is better?</h3>
            <p>A combination of both. The action of encrypting information with public-key cryptography is significantly slower than encrypting with a secret key. However the drawback of the secret-key system is that, secret keys must be transmitted either manually or through a communication channel, and there may be a chance that others can discover the secret keys during transmission.</p>
            
            <p>This is not a problem with public-key cryptography, as private keys never need to be transmitted or revealed to anyone. Each user has sole responsibility for protecting his or her private key. So, in practice public-key cryptography is used with secret-key cryptography to get the best of both worlds.</p>
          </div>
        </div>
      </div>
    </section>
  );
}